services:
  server:
    build: 
        context: ../../
        dockerfile: example/tracing/Dockerfile
    restart: always
    container_name: server
    platform: linux/aarch64
    ports:
      - "8080:8080"
    environment:
      - OTLP_ENDPOINT=http://jaeger:4318/v1/traces
    depends_on:
      - jaeger

  jaeger:
    image: jaegertracing/all-in-one:1.70.0
    ports:
      - "16686:16686"  # UI
      - "4317:4317"   
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - LOG_LEVEL=debug
    container_name: jaeger